# -*- coding: utf-8 -*-
"""exemplo1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1icP97IzYWNqNk5uVN6vF-q1v3pSTAhW_
"""

print(12345)
print('valor',12345)
print('valor = {}'.format(12345))
print(f'valor = {12345}')
print("valor",12345)
print("valor = {}".format(12345))
print(f"valor = {12345}")